#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO="Fluch-IT-Consulting/rechnungsgenerator"
TAP="fluch-it-consulting/tap"

banner "Rechnungsgenerator einrichten"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Voraussetzungen"
say "Der Tap ist öffentlich, das Repository des Generators nicht. Du brauchst"
say "deshalb Homebrew und später einen Token mit Leserecht darauf."
printf '\n'

if command -v brew >/dev/null 2>&1; then
  say "$(printf '%s✓%s Homebrew: %s' "$GREEN" "$RESET" "$(brew --version 2>/dev/null | head -1)")"
else
  warn "Homebrew fehlt. Installiere es zuerst: https://brew.sh"
  note "  https://brew.sh nennt die eine Zeile, die dafür nötig ist."
  exit 1
fi
printf '\n'
pause "Weiter mit Enter"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Token anlegen"
say "Homebrew lädt das Archiv über die GitHub-API. Dafür braucht es einen"
say "Token mit Leserecht auf genau ein Repository."
printf '\n'
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: etwa 'rechnungsgenerator brew'"
step "Resource owner: Fluch-IT-Consulting auswählen – NICHT dein eigenes Konto."
note "  Das ist der Schritt, den man am leichtesten übersieht."
step "Expiration: höchstens 366 Tage – mehr lässt die Organisation nicht zu."
step "Repository access: 'Only select repositories' anklicken,"
step "dann den Knopf 'Select repositories' und in der Liste genau"
step "Fluch-IT-Consulting/rechnungsgenerator anhaken."
note "  In der Liste steht womöglich auch Fluch-IT-Consulting/homebrew-tap."
note "  Das wird hier NICHT gebraucht – der Tap ist öffentlich."
step "Permissions: auf '+ Add permissions' klicken."
step "Im Suchfeld 'Contents' eintippen – die Liste ist alphabetisch und lang,"
step "Tippen geht schneller als Scrollen."
step "'Contents' anhaken. Dann steht unter 'Repositories' zweierlei:"
note "  Contents  · Access: Read-only"
note "  Metadata  · Access: Read-only  (Required, fügt GitHub selbst hinzu)"
step "Nur prüfen, dass bei beiden 'Read-only' steht – einstellen musst du"
step "nichts, so kommen sie herein."
note "  Mehr braucht es nicht: Homebrew lädt genau eine Datei herunter."
printf '\n'
say "Bevor du 'Generate token' drückst: Lies die Zeile darunter."
note "  'ready for use immediately' → der Token gilt sofort."
note "  Ein Hinweis auf eine Genehmigung → er steht erst auf 'Pending'."
printf '\n'
step "Jetzt 'Generate token' drücken und den Wert kopieren."
note "  GitHub zeigt ihn genau einmal."
printf '\n'
say "Die Organisation verlangt für Mitglieder die Genehmigung eines"
say "Administrators. Trifft dich das, sag Martin Bescheid: Er gibt den Token"
say "frei unter Organisationseinstellungen → Personal access tokens →"
say "Reiter 'Pending requests'."
printf '\n'
note "Der kopierte Wert bleibt danach derselbe – du kannst ihn schon jetzt"
note "einfügen und diesen Wizard nach der Freigabe noch einmal starten."
printf '\n'
pause "Weiter mit Enter"
printf '\n'
ask_secret GH_TOKEN "Token einfügen (Eingabe bleibt verdeckt):"

if [[ -z "${GH_TOKEN:-}" ]]; then
  warn "Kein Token eingegeben – ohne ihn geht es nicht weiter."
  exit 1
fi

printf '\n'
say "Ich prüfe den Token gegen das Repository, bevor er irgendwo landet."
http=$(curl -sS -o /dev/null -w '%{http_code}' \
  -H "Authorization: Bearer ${GH_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/${REPO}" 2>/dev/null || printf '000')

case "$http" in
  200) say "$(printf '%s✓%s Der Token liest %s.' "$GREEN" "$RESET" "$REPO")" ;;
  401) warn "401 – der Token ist ungültig oder falsch kopiert." ; exit 1 ;;
  403) warn "403 – mit hoher Wahrscheinlichkeit noch nicht freigegeben."
       note "  Die Organisation verlangt die Genehmigung eines Administrators."
       note "  Martin findet die Anfrage unter Organisationseinstellungen →"
       note "  Personal access tokens → Reiter 'Pending requests'."
       note "  Danach diesen Wizard einfach noch einmal starten."
       exit 1 ;;
  404) warn "404 – der Token sieht das Repository nicht."
       note "  Häufigster Grund: Als Resource owner stand das eigene Konto"
       note "  statt Fluch-IT-Consulting. Leg ihn noch einmal an."
       exit 1 ;;
  *)   warn "Unerwartete Antwort ($http). Netzwerk? Proxy?" ; exit 1 ;;
esac
printf '\n'
pause "Weiter mit Enter"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Token in die Keychain"
say "Der Token gehört nicht im Klartext in eine Datei. Dateien landen in"
say "Time-Machine-Sicherungen und – der häufigste Unfall – in Dotfiles-Repos."
say "Die Keychain deines Benutzers ist dafür der richtige Ort."
printf '\n'

KEYCHAIN_SERVICE="homebrew-github-api-token"

if ! command -v security >/dev/null 2>&1; then
  warn "Das Programm 'security' gibt es nur auf macOS."
  note "  Stelle HOMEBREW_GITHUB_API_TOKEN selbst bereit, so wie es bei dir"
  note "  üblich ist – etwa aus deinem Passwortspeicher."
  SKIPPED+=("HOMEBREW_GITHUB_API_TOKEN dauerhaft bereitstellen")
else
  case "$(basename "${SHELL:-/bin/zsh}")" in
    zsh)  RC="$HOME/.zshrc" ;;
    bash) if [[ -f "$HOME/.bash_profile" ]]; then RC="$HOME/.bash_profile"; else RC="$HOME/.bashrc"; fi ;;
    *)    RC="" ;;
  esac

  say "Ich lege zweierlei an:"
  step "einen Eintrag '$KEYCHAIN_SERVICE' in deiner Login-Keychain"
  if [[ -n "$RC" ]]; then
    step "eine kleine brew-Funktion in $RC, die ihn von dort holt"
    note "  Sie setzt die Variable NUR für den einen brew-Aufruf – nicht für"
    note "  jedes Programm, das du startest, und nicht sichtbar in 'env'."
  fi
  printf '\n'

  if confirm "So anlegen?"; then
    if security add-generic-password \
         -a "$USER" -s "$KEYCHAIN_SERVICE" -w "$GH_TOKEN" \
         -D "Homebrew GitHub API token" \
         -T /usr/bin/security -U 2>/dev/null; then
      printf '  %s✓ gespeichert%s in der Keychain: %s\n' "$GREEN" "$RESET" "$KEYCHAIN_SERVICE"
    else
      warn "Die Keychain hat den Eintrag nicht angenommen."
      SKIPPED+=("Token in der Keychain ablegen")
    fi

    printf '\n'
    say "Jetzt lese ich ihn einmal zurück."
    note "Meist fragt macOS dabei nicht: '-T /usr/bin/security' setzt genau"
    note "dieses Programm auf die Zugriffsliste des Eintrags. Kommt doch ein"
    note "Dialog, wähle 'Immer erlauben' – sonst fragt es jedes Mal wieder."
    printf '\n'
    back=$(security find-generic-password -a "$USER" -s "$KEYCHAIN_SERVICE" -w 2>/dev/null || true)
    if [[ "$back" == "$GH_TOKEN" ]]; then
      printf '  %s✓ zurückgelesen%s – der Wert stimmt.\n' "$GREEN" "$RESET"
    else
      warn "Zurücklesen hat nicht geklappt (abgebrochen oder verweigert?)."
      note "  Der Eintrag ist da; brew wird beim nächsten Mal erneut fragen."
    fi

    if [[ -n "$RC" ]]; then
      touch "$RC"
      tmp=$(mktemp)
      # Einen früheren Block dieses Wizards entfernen – und einen alten
      # Klartext-Eintrag gleich mit, falls eine ältere Fassung ihn schrieb.
      awk '
        /^# >>> rechnungsgenerator/ { skip = 1; next }
        skip && /^# <<< rechnungsgenerator/ { skip = 0; next }
        skip { next }
        /^export HOMEBREW_GITHUB_API_TOKEN=/ { found = 1; next }
        { print }
        END { if (found) print "" > "/dev/stderr" }
      ' "$RC" > "$tmp" 2>"$tmp.alt"

      {
        printf '# >>> rechnungsgenerator (Homebrew-Token aus der Keychain) >>>\n'
        printf '# Setzt den Token nur fuer den einen brew-Aufruf.\n'
        printf 'brew() {\n'
        printf '  HOMEBREW_GITHUB_API_TOKEN="$(security find-generic-password -a "$USER" -s %s -w 2>/dev/null)" \\\n' "$KEYCHAIN_SERVICE"
        printf '    command brew "$@"\n'
        printf '}\n'
        printf '# <<< rechnungsgenerator <<<\n'
      } >> "$tmp"

      if [[ -s "$tmp.alt" ]]; then
        warn "In $RC stand der Token bisher im Klartext – ich habe die Zeile entfernt."
        note "  Lag die Datei je in einer Sicherung oder einem Repo, gilt der"
        note "  Token als verbrannt: neu anlegen und den alten widerrufen."
      fi
      rm -f "$tmp.alt"

      mv "$tmp" "$RC"
      printf '  %s✓ geschrieben%s brew-Funktion → %s\n' "$GREEN" "$RESET" "$RC"
      note "  Ein früherer Block wurde ersetzt, nicht verdoppelt."
      note "  Sie gilt ab der nächsten Shell; in dieser hier reicht der Lauf."
    else
      warn "Deine Shell kenne ich nicht ($SHELL) – trag es selbst ein:"
      note "  HOMEBREW_GITHUB_API_TOKEN aus '$KEYCHAIN_SERVICE' lesen."
      SKIPPED+=("brew-Funktion in die Shell-Konfiguration eintragen")
    fi
  else
    SKIPPED+=("Token in der Keychain ablegen")
    note "Übersprungen. Für diesen Lauf reicht die Variable in dieser Shell."
  fi
fi

export HOMEBREW_GITHUB_API_TOKEN="$GH_TOKEN"
printf '\n'
pause "Weiter mit Enter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "JDK und TeX Live"
say "Der Generator läuft auf der JVM und setzt mit LuaLaTeX. Beides bringt"
say "die Formel bewusst NICHT mit."
printf '\n'

if command -v java >/dev/null 2>&1; then
  say "$(printf '%s✓%s Java: %s' "$GREEN" "$RESET" "$(java -version 2>&1 | head -1)")"
else
  warn "Kein java im PATH."
  note "  brew install openjdk"
  note "  Auf macOS 14 und älter baut Homebrew das JDK aus dem Quelltext und"
  note "  braucht volles Xcode – dort ist https://adoptium.net/ schneller."
  SKIPPED+=("Ein JDK 21 oder neuer installieren")
fi

if command -v lualatex >/dev/null 2>&1; then
  say "$(printf '%s✓%s LuaLaTeX: %s' "$GREEN" "$RESET" "$(lualatex --version 2>/dev/null | head -1)")"
else
  warn "Kein lualatex im PATH."
  note "  brew install --cask mactex-no-gui"
  note "  Danach gehört /Library/TeX/texbin in den PATH."
  SKIPPED+=("TeX Live mit lualatex installieren")
fi
printf '\n'
pause "Weiter mit Enter"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Tap hinzufügen"
say "Der Tap ist öffentlich – hier braucht es keine Zugangsdaten."
printf '\n'

if brew tap 2>/dev/null | grep -qx "$TAP"; then
  say "$(printf '%s✓%s %s ist schon eingebunden.' "$GREEN" "$RESET" "$TAP")"
else
  say "Ich führe aus:"
  note "  brew tap $TAP"
  printf '\n'
  if brew tap "$TAP"; then
    say "$(printf '%s✓%s Tap eingebunden.' "$GREEN" "$RESET")"
  else
    warn "Das Klonen ist gescheitert – vermutlich kein Netz."
    exit 1
  fi
fi
printf '\n'
pause "Weiter mit Enter"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Installieren und Probelauf"
say "Jetzt lädt Homebrew das Archiv über die API und prüft seine Prüfsumme."
printf '\n'

if brew list --formula 2>/dev/null | grep -qx "rechnungsgenerator"; then
  say "Schon installiert – ich hebe auf den neuesten Stand."
  brew upgrade "$TAP/rechnungsgenerator" || say "Nichts anzuheben."
else
  brew install "$TAP/rechnungsgenerator"
fi

printf '\n'
if command -v rechnungsgenerator >/dev/null 2>&1; then
  say "$(printf '%s✓%s %s' "$GREEN" "$RESET" "$(rechnungsgenerator --version)")"
else
  warn "rechnungsgenerator liegt nicht im PATH."
  SKIPPED+=("PATH prüfen: $(brew --prefix)/bin sollte darin vorkommen")
fi

printf '\n'
say "Probiere es aus:"
note "  rechnungsgenerator erzeuge rechnung.yaml -s stammdaten.yaml"
note "  rechnungsgenerator --help"
printf '\n'
pause "Weiter mit Enter"

finish
